# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teeth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lpp', models.FloatField(null=True)),
                ('teeth', models.TextField()),
                ('img', models.CharField(max_length=255)),
            ],
        ),
    ]
